export const SET_TASK_ONE_AS_COMPLETED: string = 'SET_TASK_ONE_AS_COMPLETED';
export const SET_TASK_TWO_AS_COMPLETED: string = 'SET_TASK_TWO_AS_COMPLETED';
export const SET_TASK_THREE_AS_COMPLETED: string = 'SET_TASK_THREE_AS_COMPLETED';
export const SET_TASK_FOUR_AS_COMPLETED: string = 'SET_TASK_FOUR_AS_COMPLETED';
export const SET_TASK_FIVE_AS_COMPLETED: string = 'SET_TASK_FIVE_AS_COMPLETED';
