export const TOGGLE_ADD_USER_MODAL: string = 'TOGGLE_ADD_USER_MODAL';
export const TOGGLE_EDIT_USER_MODAL: string = 'TOGGLE_EDIT_USER_MODAL';
export const TOGGLE_DELETE_USER_MODAL: string = 'TOGGLE_DELETE_USER_MODAL';
