export const TOGGLE_ADD_USER_MODAL: string = 'TOGGLE_ADD_USER_MODAL';
export const TOGGLE_EDIT_USER_MODAL: string = 'TOGGLE_EDIT_USER_MODAL';
export const TOGGLE_DELETE_USER_MODAL: string = 'TOGGLE_DELETE_USER_MODAL';

export const TOGGLE_ADD_ACHIEVEMENT_MODAL: string = 'TOGGLE_ADD_ACHIEVEMENT_MODAL';
export const TOGGLE_EDIT_ACHIEVEMENT_MODAL: string = 'TOGGLE_EDIT_ACHIEVEMENT_MODAL';
export const TOGGLE_DELETE_ACHIEVEMENT_MODAL: string = 'TOGGLE_DELETE_ACHIEVEMENT_MODAL';

export const TOGGLE_ADD_FAQ_MODAL: string = 'TOGGLE_ADD_FAQ_MODAL';
export const TOGGLE_EDIT_FAQ_MODAL: string = 'TOGGLE_EDIT_FAQ_MODAL';
export const TOGGLE_DELETE_FAQ_MODAL: string = 'TOGGLE_DELETE_FAQ_MODAL';

export const TOGGLE_ADD_ROLE_MODAL: string = 'TOGGLE_ADD_ROLE_MODAL';
export const TOGGLE_EDIT_ROLE_MODAL: string = 'TOGGLE_EDIT_ROLE_MODAL';
export const TOGGLE_DELETE_ROLE_MODAL: string = 'TOGGLE_DELETE_ROLE_MODAL';
