export const STORE_ACHIEVEMENT_TITLE: string = 'STORE_ACHIEVEMENT_TITLE';
export const STORE_ACHIEVEMENT_DESCRIPTION: string = 'STORE_ACHIEVEMENT_DESCRIPTION';
export const STORE_ACHIEVEMENT_DATE: string = 'STORE_ACHIEVEMENT_DATE';
export const ACHIEVEMENT: string = 'ACHIEVEMENT';
export const DELETE_ACHIEVEMENT: string = 'DELETE_ACHIEVEMENT';